### ISSUE TITLE
no blocking anymore

### ISSUE THREAD

**Issue by stefabaldi** [pixeltris/TwitchAdSolutions#220]
when the ads come up the stream start loading and when i try to refresh the page the ad isn't blocked. Other times i see the "blocking mid-roll ads" but the ads aren't blocked at all.

**Comment by revunix** [comment]
Use TTV LOL PRO

**Comment by phireblast** [comment]
> Use TTV LOL PRO

this still happens with TTV LOL PRO

**Comment by pixeltris** [comment]
I can reproduce this. Under `video-swap-new` I've observed a few different things:

- Ads being displayed
- Player load errors
- Stream resolution getting stuck at 240p

I think it's mostly midroll issues but may also impact prerolls. I'll look at possible solutions.

**Comment by Fe-n** [comment]
> I can reproduce this. Under `video-swap-new` I've observed a few different things:
> 
>     * Ads being displayed
> 
>     * Player load errors
> 
>     * Stream resolution getting stuck at 240p
> 
> 
> I think it's mostly midroll issues but may also impact prerolls. I'll look at possible solutions.

Thank you.  I've also noticed issues with `video-swap-new` the last few days, but I wasn't sure if it was a transient issue or possibly caused by my  sort-of out-of-date BTTV (the Firefox release lags behind the other releases) and hadn't looked into it more yet.

My experience has been:

* No pre-roll ads observed when first loading a stream.  The low-res embed player seems to be correctly used when they would otherwise play.  However, the higher resolution is not swapped to, and unlike at some points in the past, pausing and then unpausing the player does not force a switch.  Refreshing the page will either result in ads playing (I think this happened once?) or the stream playing normally at selected resolution.
* When mid-roll ads are meant to be played, the stream simply stops playback.  Pausing and then un-pausing the player will result in the ads playing.

**Comment by JTJutajoh** [comment]
In the meantime, I've found that I can fix the "stuck at 240p" part by waiting a few minutes for ads to finish, then using the FFZ "Reset Player" button.

**Comment by pixeltris** [comment]
Should be fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/9bd481a833341911ac39412dc4abcc41f911af8f

**Comment by stefabaldi** [comment]
updated today the new version, now the loading neither starts, ads start normally

**Comment by Gamerboi520** [comment]
even with this patch its still broken
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/470bbccb-ed5b-405e-b7e9-97a118940012)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/a5104ff6-854a-486d-869d-a4c308fd861e)

**Comment by pseeghosts** [comment]
tried all the url options and none of them held the ads :/
