### ISSUE TITLE
Vaft not properly functioning on Brave

### ISSUE THREAD

**Issue by Baaugh** [pixeltris/TwitchAdSolutions#383]
I have attempted to use vaft on brave. It had begun ads even after I had changed it to perma. Now when I had switched to "video-swap-new" it worked perfectly fine. I am wondering if there is something I am doing wrong I have just followed what had been shown.

**Comment by pixeltris** [comment]
Hopefully fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/accf04aa3619b6dd40ee1fe63f2d3522bfc5d75d

**Comment by Mightyena31** [comment]
> Hopefully fixed by [accf04a](https://github.com/pixeltris/TwitchAdSolutions/commit/accf04aa3619b6dd40ee1fe63f2d3522bfc5d75d)

@pixeltris 

Im still getting ads with Brave and I updated BOTH scripts on tampermonkey, I disabled brave guard and ublock origin to test with just tampermonkey and both scripts im getting ads

**Comment by Baaugh** [comment]
> Hopefully fixed by [accf04a](https://github.com/pixeltris/TwitchAdSolutions/commit/accf04aa3619b6dd40ee1fe63f2d3522bfc5d75d)

so I no longer get ads and audio quality isn't the worst but it still lowers the quality to the other version.
