### ISSUE TITLE
video swap new no longer working

### ISSUE THREAD

**Issue by angrypeestain** [pixeltris/TwitchAdSolutions#450]
So it seems like the script is no longer working? I get the message on the top left saying "blocking ads" but the ad is still running

**Comment by AmaZeroMmu** [comment]
I am seeing this as of today as well

**Comment by IdleUrsid** [comment]
It worked for me till an hour ago (as of writing). Saw it trigger on an pre-roll so far.

**Comment by angrypeestain** [comment]
> It worked for me till an hour ago (as of writing). Saw it trigger on an pre-roll so far.

yes same for me

**Comment by mu71ny** [comment]
Some ADs get blocked but some get through; both vaft & VSN. Kept refreshing until it worked

**Comment by pixeltris** [comment]
Looks like the low resolution stream isn't working anymore. In https://github.com/pixeltris/TwitchAdSolutions/commit/53c18325bc83d32734e4da3e54e97bf03223157b I've changed `vaft` to use the embed player type as a fallback which will show the "Preparing your stream..." screen. This seems especially prone to freezing, needs to be addressed with the other freezing issues.

For `video-swap-new` change the following line of code

https://github.com/pixeltris/TwitchAdSolutions/blob/53c18325bc83d32734e4da3e54e97bf03223157b/video-swap-new/video-swap-new.user.js#L32

to

```js
scope.OPT_BACKUP_PLAYER_TYPE = 'embed';
```

This will display the "Preparing your stream..." screen under `video-swap-new`.

Not sure what I will do going forward. `vaft` will probably be the way to go if there are no more low resolution streams. The freezing issues definitely need to be addressed though.

*I didn't switch to the `embed` player type for `video-swap-new` in the main code yet because it didn't seem that great from my testing and I think they are A/B testing right now so just leaving it as it is for the time being.*

**Comment by swzrrx** [comment]
same for me any fix?

**Comment by rafelolv** [comment]
Problem started a few mins ago
"Blocking ads" in the top left corner, but the ad is still showing

**Comment by ArchiiManiaK** [comment]
yeah the battle never ends.

**Comment by CarbonatedPastries** [comment]
For anyone still experiencing the issue, make sure your script has been updated. I was running the Userscript version and my Userscript extension hadn't yet update it; Advertisements were blocking again once I did. It sounds like exploration of other solutions or mitigations is in order, but for the time being this works.

**Comment by cardinalfan3000** [comment]
Yeah i'm getting the same thing. It says blocking ads on the top right but the ad still shows

**Comment by affdeus** [comment]
same happening here but looks like is always the same ads that is not being blocked on any channel that plays it (like the new Fanta Halloween cans)... maybe is some new "wave". Others ads seems to be ok since it show the "blocking midroll adds" and they don't play.
using the `userResourcesLocation... ` method

**Comment by cardinalfan3000** [comment]
Idk I keep getting it after every ad

**Comment by undefinedid** [comment]
That's strange because the extension `Alternate Player for Twitch.tv` still has access to the low-resolution stream during ads.
I switched to it to avoid the waiting picture and it works just as `vaft` and `video-swap-new` scripts before.

**Comment by salvadorzombie** [comment]
Like CarbonatedPastries suggested, updating fixed it for me. I just turned the extension off and on again, now it's blocking like it used to.

And honestly if it breaks again, I can't deal with the "Preparing your stream..." stuff, it's the same as an ad but even worse, because there's *nothing* playing. But *so far* it seems fine (fingers crossed).

EDIT: Nope, some ads get through still. Looks like it's not fixed.

**Comment by salvadorzombie** [comment]
Question for pixeltris - how would we change the line in the script itself? As far as I've seen, we just have the URL that links to the script, I don't know how I would alter the script that's on the page.

**Comment by angrypeestain** [comment]
Ok this is strange.... the script works perfectly fine on my notebook without any changes/updates but not on my Desktop....

**Comment by IdleUrsid** [comment]
> @salvadorzombie Question for pixeltris - how would we change the line in the script itself? As far as I've seen, we just have the URL that links to the script, I don't know how I would alter the script that's on the page.

Within the script manager that you use for the userscript (eg. greasemonkey, violentmonkey, firemonkey etc...). Go within that add-on/manager, find the script, go to line 32 and edit the line. Don't forget to save the changes and see if it works, or not, afterwards with a refresh of the page.

**Comment by angrypeestain** [comment]
@pixeltris So it seems like when I select the "popout player" in the twitch video options on a stream it still blocks ads ... other than that the script also works without any updates/changes/whatever on my notebook.... its really strange

**Comment by Stoarr** [comment]
It's really strange for me. I get one ad and after a couple seconds a Twitch Turbo banner appears on the button of the ad. When the ad is finished, it goes back to normal blocking

**Comment by pixeltris** [comment]
In https://github.com/pixeltris/TwitchAdSolutions/commit/7240e9855ec73a2aa6ff60679c3386fbf1e75732 I've changed the method used for the low res stream which seems to work from my testing but I imagine they will also patch that within a day or so.

Additionally I've changed `video-swap-new` to use the embed player as a fallback if the low res stream fails which should prevent ads from being shown but you will see either "Preparing your stream..." (prerolls) or "Commercial break in progress" (midrolls). @undefinedid I've added support for the method that `Alternate Player for Twitch.tv` uses which works on midrolls (may not work on all streams depending on the given streamer's Picture-by-Picture settings).

**Comment by ArchiiManiaK** [comment]
I don't know, working for chrome again with ublock origin development build , but still not on firefox Ublock origin.

**Comment by tfoutfou** [comment]
same , it doesn't work anymore , show blocking add , but add still start (a few second after)

i don't know if this is related , but i was watching twitch no problem , then i restarted my computer and firefox just upgraded , this is the only thing that have changed for me !  

was on twitch 2 min earlier , and it stop working right after firefox update , no delay

**Comment by pixeltris** [comment]
If you're using the uBlock Origin version you'll want to grab the latest permalink. If you're using the non-permalink uBlock Origin version uBlock Origin often caches the script so even though the script is updated on github it'll still use what's cached. Use the latest permalink to avoid this problem.

I recommend using the userscript version.

**Comment by tfoutfou** [comment]
fixed thanks !

Since i am here , what are the cause and limitation for me not beeing able to view stream in 1440p source when available ?

**Comment by angrypeestain** [comment]
So it seems like it works for me again even tho I'm using the old script lol

**Comment by Psych32** [comment]
used the script from the ublock permalink it still doesnt block ads. Just plays them in low quality

**Comment by redetalaw** [comment]
To add info here. 

Using violentmonkey and the userscript verstion in 2 different firefox installations (one portable, one normal).

In the portable installation video-swap isn't working, ads go through. Using vaft has been successful.

In the normal installation, video-swap works as it has been for the past year. Nothing changed there. 

Same PC, same user, just two different installations of firefox, both using violentmokey for the userscript.

[EDIT]Windows 11. Both firefox at latest version (143.0.4).

**Comment by dvanco** [comment]
I don't know that my comments are particularly useful, but -
Brave 1.82.173 (Official Build) (arm64)  (MacOS 15.6.1)

Neither vaft or video-swap-new working (both show as current) via Violentmonkey.
vaft causes constant freezing so I can't really assess the ad blocking ability
video-swap-new also freezing a bit, or simply shows the "Twitch Ads Playing" screen for 2+ minutes while ads play (presumably in the background).

**Comment by zentrextrov** [comment]
> I don't know that my comments are particularly useful, but - Brave 1.82.173 (Official Build) (arm64) (MacOS 15.6.1)
> 
> Neither vaft or video-swap-new working (both show as current) via Violentmonkey. vaft causes constant freezing so I can't really assess the ad blocking ability video-swap-new also freezing a bit, or simply shows the "Twitch Ads Playing" screen for 2+ minutes while ads play (presumably in the background).

I am on brave and it's still working for me

**Comment by dlmcglade** [comment]
I had an interesting experience today on twitch. So, Battlefield 6 was released today, and my standard uBlock Origin + pixeltris/TwitchAdSolution script was working fine until I started watching a BF6 stream. On BF6 streams, the script failed. When I went to another stream with a different game, the existing solution worked fine. Going back to a BF6 stream, but a different streamer, it failed again. Almost as if twitch enabled a different configuration setup just for today's big BF6 release. Watching other streams now, the script we've been using all along is working again.

Is it possible that twitch has a (more) unblockable method they they pull out of the box just on occasions when they're expecting a big viewer base, such as in game releases, and they put it away when the hype is over, to avoid exposure, where we'll invariably figure out a way to block whatever method that is?

**Comment by salvadorzombie** [comment]
Just had vaft let through a Playstation ad, running Firefox.

Switched to video swap new, that seems to be working. At least for now.

**Comment by angrypeestain** [comment]
> I had an interesting experience today on twitch. So, Battlefield 6 was released today, and my standard uBlock Origin + pixeltris/TwitchAdSolution script was working fine until I started watching a BF6 stream. On BF6 streams, the script failed. When I went to another stream with a different game, the existing solution worked fine. Going back to a BF6 stream, but a different streamer, it failed again. Almost as if twitch enabled a different configuration setup just for today's big BF6 release. Watching other streams now, the script we've been using all along is working again.
> 
> Is it possible that twitch has a (more) unblockable method they they pull out of the box just on occasions when they're expecting a big viewer base, such as in game releases, and they put it away when the hype is over, to avoid exposure, where we'll invariably figure out a way to block whatever method that is?

this is very weird i agree...

but otherwise the script just works fine for me ... nothing got through using newest FF with the updated "video swap new" script

**Comment by dlmcglade** [comment]
> > I had an interesting experience today on twitch. So, Battlefield 6 was released today, and my standard uBlock Origin + pixeltris/TwitchAdSolution script was working fine until I started watching a BF6 stream. On BF6 streams, the script failed. When I went to another stream with a different game, the existing solution worked fine. Going back to a BF6 stream, but a different streamer, it failed again. Almost as if twitch enabled a different configuration setup just for today's big BF6 release. Watching other streams now, the script we've been using all along is working again.
> > Is it possible that twitch has a (more) unblockable method they they pull out of the box just on occasions when they're expecting a big viewer base, such as in game releases, and they put it away when the hype is over, to avoid exposure, where we'll invariably figure out a way to block whatever method that is?
> 
> this is very weird i agree...
> 
> but otherwise the script just works fine for me ... nothing got through using newest FF with the updated "video swap new" script

Now that the BF6 hype is over (or whatever coincided with the BF6 hype), everything is back to normal for me, and video swap is working.

**Comment by dvanco** [comment]
I watch mainly "riffing" channels - mst3k, rifftrax, dumb-insdustries, etc - all are the same. When ads get blocked I get the "Twitch Ads are Playing" splash screen and a countdown to when the video will resume - or just a complete crash of Twitch.  I've tried on and off a VPN. 

I do have uBlock Origin installed but I don't use it on Twitch. If it's possible that will work better I can give it a try. 

If anyone wants to offer advice on what to look at - shields in Brave, etc, I'm happy to try. 

Saying "Brave works for me" with zero details isn't very useful information.

**Comment by pixeltris** [comment]
@dvanco there are two types of ads; preroll / midroll. If you're served a preroll ad and the low resolution stream fails you'll see a screen which says "Preparing your stream..." which will last exactly 15 seconds. If you're served a midroll ad and the low resolution stream fails it will use the Picture-by-Picture stream (it should also be low resolution I think) and if that fails you'll see a screen which says "Commercial break in progress" which will be the full duration of the midroll ad.

You can read some info about Picture-by-Picture here: https://help.twitch.tv/s/article/picture-by-picture-ads

Based on what it says it should work on all channels which are Twitch partners or affiliates. From my testing on midrolls if I disable the low resolution backup and just rely on Picture-by-Picture it works on the streams you linked (mst3k / rifftrax, I didn't any get a midrolls on dumbtelevision after waiting 50 minutes).

I can't say why both the low resolution stream and the Picture-by-Picture stream fails for you.

> or just a complete crash of Twitch

There is a bug in the following code where sometimes the requester cancels the given request which makes it appear as if the stream goes offline. I need to look into how it should correctly handle such situations. It's pretty rare from my testing but that might vary between different machines.

https://github.com/pixeltris/TwitchAdSolutions/blob/c8749a2846046232c3770fc3122131f1f06eb837/video-swap-new/video-swap-new.user.js#L409-L412

**Comment by dvanco** [comment]
Thanks for the detail - I'll do some further testing.

**Comment by Geant200** [comment]
Thank you for your efforts in getting us a strong fix, thank you in advance.

**Comment by david-UT99** [comment]
i'm using 'ttv lol pro v1' proxy and 2 weeks ago it started that annoying 'stream is offline' bs for only 1 channel. so, i tried your scripts instead, but no difference.

but the original channel i was struggling with to load now works flawlessly, & twitch has decided i can't load a different stream i follow & successfully blocked ads on daily for 8 months or whatever.

**Comment by VTOLgorgon** [comment]
I used to use TamperMonkey for video-swap-new and it stopped working. Switched to ViolentMonkey and added video-swap-new, works again as intended. This is in combination with adGuard Extras. Firefox.

Purple and TTVLOL didnt seem to help and at best would offer "Commercial Break In Progress" purple screen.

**Comment by JayVez94** [comment]
It's still not working for me. It blocks ads when I first open streams but when midroll comes on it says "Blocking Midroll Ads" and I see the "Commercial Break in Progress" screen. Using the permalink as well and still didn't work.

**Comment by Xe11o** [comment]
I updated the script in tampermonkey with the code from that commit: https://github.com/pixeltris/TwitchAdSolutions/commit/53c18325bc83d32734e4da3e54e97bf03223157b and at first last week I was getting the same result reported by some here, the big twitch "ad break in progress" splash screen or whatever it was. For the past day or 2 though it seems to have returned to the previous behaviour 👍

**Comment by dvanco** [comment]
TL:DR: Giving up on Brave.  FF is fine. 

I think Twitch may be making changes based on browsers or something. I can't get it (blocking midroll ads) to work with Brave, but with FireFox it's working fine (same laptop). I've got another Macbook Pro with Intel silicon and FF works fine on that one as well (have not tried Brave there).  I suppose it could be some conflict between Brave Shields, but I've got them lower than I like and still no bueno. The Brave devs are certainly doing their best to piss off Amazon/Twitch, so I'm sort of not surprised.

**Comment by swzrrx** [comment]
any fixes yet still?

**Comment by Geant200** [comment]
Not yet ^^.

**Comment by pixeltris** [comment]
The fix for this was the commit 2 weeks ago https://github.com/pixeltris/TwitchAdSolutions/commit/7240e9855ec73a2aa6ff60679c3386fbf1e75732 I'll keep an eye out for any further changes but I'm closing this issue as it has been addressed. Sorry to anyone who can't get it working, my recommendation would be to double check you're on the latest version and that you don't have any conflicting extensions/scripts. Alternatively try another solution linked in the readme.
